name: Leibale


on:
  push:
  
  workflow_dispatch:
    inputs:
      image_name:
        required: true
        type: string
      arch:
        required: false
        type: string
        default: x86_64
      osnick:
        required: true
        type: string
        
jobs:
  build-redis:
    name: leibale
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
